@startuml
<style>
title{
	FontName JetBrains Mono
	FontStyle Bold
	FontSize 14
}
componentDiagram{
	FontName JetBrains Mono
	FontSize 12
}

</style>

' !include https://raw.githubusercontent.com/ptrkcsk/one-dark-plantuml-theme/v1.0.0/theme.puml

' title Diagrama de Despliegue\nSistema de Reserva\npara Plataforma de Envíos InstaYA
actor "Usuario"
' node node [
' <b>Sistema de Login
' ----
' Inicializa el panel de usuario
' Registra Usuario

' ]

node "Dispositivo Cliente" <<device - Windows, Linux, Mac, IOS, Android>> {

    node Navegador <<Aplicación>> {
    }

}

node "Servidor Web" <<device>> {
    node "Aplicación" <<React.js>> {
        artifact Bootstrap <<artifact>>
        artifact React.js <<artifact>>
        ' [Login]
        ' [Registro]
        ' [Listado Órdenes]
        ' [Registro Órdenes]
        ' [Actualización Órdenes]

    }
    component "Servidor HTTP"
    node "Interfaz BD - Node.Js" <<Execution Environment>> as IBD {
        node "Express.js" {
            [Express Middleware]
            [Express Routing]

        }

    }
}

node "Servidor BD" <<device>> {

    database "MongoDB"
    component "Almacenamiento"
}

' node ISP <<Access Point>> {
'     rectangle "???"
' }
' node "ISP"


[Usuario] <--> Navegador : UI
' Navegador <--> ISP : HTTP/HTTPS
' ISP <--> [Servidor HTTP] : HTTP/HTTPS
Navegador <--> [Servidor HTTP] : HTTP/HTTPS
Aplicación <-> [Servidor HTTP]
Aplicación <-> IBD
[Servidor HTTP] <--> IBD


' [Navegador] <--> [Servidor HTTP] : <<HTTP/HTTPS>>\nISP
IBD <--> [MongoDB] : TCP/IP
[MongoDB] <-> [Almacenamiento]

' [Login] -> [Registro]
' [Login] --> [Listado Órdenes]
' [Listado Órdenes] -> [Actualización Órdenes]
' [Listado Órdenes] --> [Registro Órdenes]

@enduml